### ISSUE TITLE
enum ".value"s are being HTML encoded

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/chimera#104]
This may be happening somewhere in the `mstch` templating code. E.g.:

```
.value("Delegate", dart::common::detail::ComposeData&lt;dart::common::detail::CompositeData&lt;std::map&lt;std::type_index, std::unique_ptr&lt;dart::common::Aspect::Properties, std::default_delete&lt;dart::common::Aspect::Properties&gt; &gt;, std::less&lt;std::type_index&gt;, std::allocator&lt;std::pair&lt;const std::type_index, std::unique_ptr&lt;dart::common::Aspect::Properties, std::default_delete&lt;dart::common::Aspect::Properties&gt; &gt; &gt; &gt; &gt;, dart::common::detail::GetProperties&gt;, dart::common::detail::GetProperties, dart::dynamics::BodyNode&gt;::DelegateTag::Delegate)
```

**Comment by jslee02** [comment]
Related PR: #117

**Comment by jslee02** [comment]
In summary, we should either (1) use triple mustache to get unescaped HTML, which is [suggested by the mustache specification](http://mustache.github.io/mustache.5.html) or (2) [disable the escaping function](https://github.com/no1msd/mstch#custom-escape-function), which is allowed by [`no1msd/mstch`](https://github.com/no1msd/mstch).

I'm inclined to (1) that obeys the specification. 

@mkoval @psigen Thoughts?
