### ISSUE TITLE
Don't generate `sources.txt` when binding generation is failed

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/chimera#114]
Chimera generates `sources.txt` even when it fails to generate the bindings (*.cpp files). This makes re-running `make` in the consumer project (e.g., `dartpy`) not to re-run `chimera` to generate the bindings again but just try to build the bindings assuming they are all generated.

The right fix is to modify Chimera to only write `sources.txt` after it is completely done. So `make` will re-run `chimera` to generate the bindings.

The in-the-meantime solution would be deleting `sources.txt` before re-run `make` when the binding generation is failed.

This issue was discovered in the chat with @mkoval .

**Comment by psigen** [comment]
This is actually [a legit bug in CMake <3.3](http://stackoverflow.com/a/41642161) because the output of a failing command is not supposed to be considered valid by subsequent CMake steps.

I think we should just implement the workaround suggested in that post.

**Comment by mkoval** [comment]
Fixed by #134.
