### ISSUE TITLE
Update README.md for long key case

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/chimera#118]
[`yaml-cpp` doesn't allow more than 1024 characters for a single line key](https://github.com/jbeder/yaml-cpp/blob/master/src/simplekey.cpp#L111). For longer key, we should use [multi-line key](http://stackoverflow.com/a/36295084). It would be good to mention about this on the readme.

**Comment by psigen** [comment]
Good catch! Maybe we should make an FAQ section for weird errors people
might see.

**Comment by jslee02** [comment]
I've created the wiki page and added this to the FAQ section. I might be adding more items here before it becomes stable and is moved to `README.md` if needed.
