### ISSUE TITLE
Required items in configuration file?

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/chimera#120]
According to the code (e.g., [this](https://github.com/personalrobotics/chimera/blob/master/src/configuration.cpp#L280) and [this](https://github.com/personalrobotics/chimera/blob/master/src/configuration.cpp#L485)), the items are seemed to be optional. However, `yaml-cpp` 0.5.2 throws exception for the current implementation of Chimera at [here](https://github.com/personalrobotics/chimera/blob/master/src/configuration.cpp#L398) (`node.Type()`).

`yaml-cpp` 0.5.2 [creates a *zombie node*](https://github.com/jbeder/yaml-cpp/blob/release-0.5.2/include/yaml-cpp/node/impl.h#L373) if the key doesn't exist (e.g., [`template_config["prebody"]`](https://github.com/personalrobotics/chimera/blob/master/src/configuration.cpp#L284)), and the zombie node throws an exception when [`Node::Type()` is called](https://github.com/personalrobotics/chimera/blob/master/src/configuration.cpp#L398). This is the cause of the errors reported in #119.

I suggest that we perform the validity check in advance, and, if it's not valid, we print warnings and just return.

**Comment by psigen** [comment]
We should change the items to be optional.
