### ISSUE TITLE
Make Boost.Python optional dependency

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/chimera#139]
Boost.Python dependency is added by #135, but it is only necessary for the tests. We could make it optional and add test directory only when Boost.Python is installed. Also, it would be good to print a warning encouraging installing it for tests.

**Comment by psigen** [comment]
Maybe we could make a section of the tests CMakeList.txt for "Boost.Python" tests that only runs when it is detected?

We have been talking for a while about making multiple language bindings, and tests for each one would probably need a different set of optional libraries.

**Comment by jslee02** [comment]
> Maybe we could make a section of the tests CMakeList.txt for "Boost.Python" tests that only runs when it is detected?

:+1: 


> We have been talking for a while about making multiple language bindings, and tests for each one would probably need a different set of optional libraries.

How is that possible? I thought Boost.Python is only for C++ --> Python.

**Comment by psigen** [comment]
> How is that possible? I thought Boost.Python is only for C++ --> Python.

That's correct, but nothing about _chimera_ is specific to `Boost.Python`.  For example, we have been considering making templates to generate `pybind11` code, which we might want unit tests for.

**Comment by jslee02** [comment]
> For example, we have been considering making templates to generate pybind11 code, which we might want unit tests for.

That sounds cool! I've also wondered if Chimera can do that. According to their [benchmark](http://pybind11.readthedocs.io/en/master/benchmark.html), `pybind11` has some advantages over `Boost.Python`.

**Comment by jslee02** [comment]
Yes! Looking at the CMake scripts for testing, the `boost.python` and `pybind11` tests are ignored when the necessary dependency isn't detected.
