### ISSUE TITLE
`sources.txt` in unit tests seem to have double entries.

### ISSUE THREAD

**Issue by psigen** [personalrobotics/chimera#184]
From `build/test/02_class/test_class_pybind11/sources.txt`

```
_ZN10test_class17test_nested_class3PetE.cpp
test_class_pybind11.cpp
_ZN10test_class17test_nested_class3PetE.cpp
test_class_pybind11.cpp
```

I am not sure why this is happening.  It does not impede compilation, but it is weird.

**Comment by jslee02** [comment]
Closing as this seems not an issue anymore. Not sure when this is resolved though. Feel free to reopen if it's not the case.
